### ISSUE TITLE
Unknown prop `disableFocusRipple` on <div> tag

### ISSUE THREAD

**Issue by EmirGluhbegovic** [sautumn/material-ui-autocomplete-google-places#13] opened 2017-07-10 10:56 UTC
As soon as I type a into the GooglePlaceAutocomplete component I see the following message in the console: Warning: Unknown prop `disableFocusRipple` on <div> tag. Remove this prop from the element...

**Comment by stelro** [comment] 2017-08-07 09:24
I have the same issue. Any fix for this?

**Comment by ghost** [comment] 2017-08-19 22:39
Same here...

**Comment by 462960** [comment] 2017-11-13 06:43
The same problem:
I use `<GooglePlaceAutocomplete/>`. 
It works as intended but console says in red "Unknown prop disableFocusRipple on div tag" I tried to shut it down in diff ways, none of them removes warning: 
**1) As React docs says** https://reactjs.org/warnings/unknown-prop.html 
`const {disableFocusRipple, ...rest} = props; <GooglePlaceAutocomplete {...rest}/>`
**2) As Material UI says** 
`<GooglePlaceAutocomplete disableFocusRipple={true}/>` 
**3) As I found on the Web.** 
`componentDidMount(){    GooglePlaceAutocomplete.defaultProps.disableFocusRipple = true;  }`
**4) I tried to remove**
`<ErrorBoundary>` wrapper at the root component. 
Please, I'd like to get know: 
1) What is disableFocusRipple and why it behaves in such a way? 
2) How to get rid of that warning text?

**Comment by talmog** [comment] 2018-01-07 10:47
<GooglePlaceAutocomplete disableFocusRipple={true}/> worked for me.

**Comment by FDiskas** [comment] 2018-01-12 14:07
this will be not visible in production :mask:

**Comment by archcorsair** [comment] 2019-01-11 03:03
Apologies, the package maintainers have not been able to work on this package in some time. However there are plans for a complete rewrite & support for latest MUI 
very soon. Good luck & sorry for the inconvenience!

**Closed as completed by archcorsair** 2019-01-11 03:03 UTC
